import { BODY_TYPES, ORBIT_MODES, DEFAULTS, uid, colorToHex } from "./config.js";

function hashString(str = "seed") {
  let h = 1779033703 ^ str.length;
  for (let i = 0; i < str.length; i += 1) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return () => {
    h = Math.imul(h ^ (h >>> 16), 2246822507);
    h = Math.imul(h ^ (h >>> 13), 3266489909);
    return (h ^= h >>> 16) >>> 0;
  };
}

function mulberry32(seedInt) {
  return function rand() {
    let t = (seedInt += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function makeRng(seedText = `${Date.now()}`) {
  const seed = hashString(seedText)();
  return mulberry32(seed);
}

function pick(rng, items) {
  return items[Math.floor(rng() * items.length)];
}

function range(rng, min, max) {
  return min + (max - min) * rng();
}

function round(value, digits = 2) {
  const pow = 10 ** digits;
  return Math.round(value * pow) / pow;
}

const STAR_PRESETS = [
  { name: "Blue Main Sequence", color: "#86b6ff", mass: 420000, radius: 72, glow: 1.3 },
  { name: "White Star", color: "#f8f8ff", mass: 310000, radius: 62, glow: 1.15 },
  { name: "Yellow Star", color: "#ffd76a", mass: 250000, radius: 56, glow: 1.0 },
  { name: "Orange Star", color: "#ffad5a", mass: 190000, radius: 48, glow: 0.95 },
  { name: "Red Dwarf", color: "#ff7d5c", mass: 120000, radius: 38, glow: 0.85 }
];

const PLANET_PRESETS = [
  { family: "rocky", color: "#9aa3b2", mass: 180, radius: 12 },
  { family: "desert", color: "#d7a867", mass: 210, radius: 14 },
  { family: "temperate", color: "#70c98d", mass: 260, radius: 16 },
  { family: "ocean", color: "#58a8ff", mass: 290, radius: 17 },
  { family: "ice", color: "#d3f1ff", mass: 190, radius: 14 },
  { family: "gas giant", color: "#ccb48a", mass: 2400, radius: 31 }
];

function makeRoot() {
  return {
    id: "root-system",
    type: BODY_TYPES.ROOT,
    name: "System Root",
    parentId: null,
    visible: false,
    childrenIds: [],
    mass: 1,
    radius: 1,
    color: colorToHex("#ffffff"),
    glow: 0,
    info: {
      summary: "Top-level system container",
      details: "Invisible anchor used by the renderer and simulation."
    },
    orbit: { mode: ORBIT_MODES.ROOT, phase: 0 }
  };
}

function makeStar(rng, index, overrides = {}) {
  const preset = overrides.preset ?? pick(rng, STAR_PRESETS);
  return {
    id: uid("star"),
    type: BODY_TYPES.STAR,
    name: overrides.name ?? `Star ${index + 1}`,
    parentId: overrides.parentId ?? "root-system",
    visible: true,
    childrenIds: [],
    mass: round(overrides.mass ?? preset.mass * range(rng, 0.85, 1.15), 2),
    radius: round(overrides.radius ?? preset.radius * range(rng, 0.9, 1.12), 2),
    color: colorToHex(overrides.color ?? preset.color),
    glow: round(overrides.glow ?? preset.glow, 2),
    info: {
      summary: overrides.summary ?? preset.name,
      details: overrides.details ?? `${preset.name} configured for this generated system.`
    },
    orbit: {
      mode: overrides.orbitMode ?? ORBIT_MODES.STATIC,
      phase: round(range(rng, 0, Math.PI * 2), 4),
      semiMajorAxis: overrides.semiMajorAxis ?? 0,
      eccentricity: overrides.eccentricity ?? 0,
      clockwise: overrides.clockwise ?? false,
      primaryId: overrides.primaryId ?? null,
      secondaryId: overrides.secondaryId ?? null,
      partnerId: overrides.partnerId ?? null,
      figure8Scale: overrides.figure8Scale ?? 0
    }
  };
}

function makePlanet(rng, index, parentId, orbitOverrides = {}, label = "Planet") {
  const preset = orbitOverrides.preset ?? pick(rng, PLANET_PRESETS);
  return {
    id: uid("planet"),
    type: BODY_TYPES.PLANET,
    name: orbitOverrides.name ?? `${label} ${index + 1}`,
    parentId,
    visible: true,
    childrenIds: [],
    mass: round((orbitOverrides.mass ?? preset.mass) * range(rng, 0.75, 1.35), 2),
    radius: round((orbitOverrides.radius ?? preset.radius) * range(rng, 0.85, 1.25), 2),
    color: colorToHex(orbitOverrides.color ?? preset.color),
    glow: 0,
    info: {
      summary: orbitOverrides.summary ?? `Autogenerated ${preset.family} world`,
      details: orbitOverrides.details ?? `Prototype ${preset.family} body. Surface and atmosphere details are intentionally left generic for later passes.`
    },
    orbit: {
      mode: orbitOverrides.mode ?? ORBIT_MODES.KEPLER,
      phase: round(orbitOverrides.phase ?? range(rng, 0, Math.PI * 2), 4),
      semiMajorAxis: round(orbitOverrides.semiMajorAxis ?? 260, 2),
      eccentricity: round(orbitOverrides.eccentricity ?? range(rng, 0, 0.12), 3),
      clockwise: Boolean(orbitOverrides.clockwise ?? (rng() > 0.5)),
      primaryId: orbitOverrides.primaryId ?? parentId,
      secondaryId: orbitOverrides.secondaryId ?? null,
      figure8Scale: round(orbitOverrides.figure8Scale ?? 120, 2),
      inclination: round(orbitOverrides.inclination ?? range(rng, -0.15, 0.15), 3),
      binarySeparation: orbitOverrides.binarySeparation ?? 0,
      partnerId: orbitOverrides.partnerId ?? null
    }
  };
}

function makeBarycenter(name, parentId, orbit = {}) {
  return {
    id: uid("bary"),
    type: BODY_TYPES.BARYCENTER,
    name,
    parentId,
    visible: false,
    childrenIds: [],
    mass: 1,
    radius: 1,
    color: colorToHex("#ffffff"),
    glow: 0,
    info: {
      summary: "Barycenter",
      details: "Invisible pivot body for binary pairs."
    },
    orbit: {
      mode: orbit.mode ?? ORBIT_MODES.KEPLER,
      phase: orbit.phase ?? 0,
      semiMajorAxis: orbit.semiMajorAxis ?? 0,
      eccentricity: orbit.eccentricity ?? 0,
      clockwise: Boolean(orbit.clockwise),
      primaryId: orbit.primaryId ?? parentId,
      secondaryId: orbit.secondaryId ?? null,
      figure8Scale: orbit.figure8Scale ?? 0,
      inclination: orbit.inclination ?? 0
    }
  };
}

function linkChild(bodies, parentId, child) {
  bodies.push(child);
  const parent = bodies.find((b) => b.id === parentId);
  if (parent) parent.childrenIds.push(child.id);
}

function addMoons({ rng, bodies, planet, maxMoons }) {
  const moonCount = Math.floor(rng() * (maxMoons + 1));
  for (let i = 0; i < moonCount; i += 1) {
    const moon = makePlanet(rng, i, planet.id, {
      name: `${planet.name} - Moon ${i + 1}`,
      mode: ORBIT_MODES.KEPLER,
      semiMajorAxis: round(planet.radius * 4 + (i + 1) * range(rng, 16, 28), 2),
      eccentricity: round(range(rng, 0, 0.08), 3),
      phase: range(rng, 0, Math.PI * 2),
      mass: round(planet.mass * range(rng, 0.01, 0.08), 2),
      radius: round(Math.max(4, planet.radius * range(rng, 0.18, 0.4)), 2),
      color: pick(rng, ["#cfd6df", "#aab8cc", "#d8d1c3", "#9bb7ff"]),
      summary: `Autogenerated moon of ${planet.name}`,
      details: `Placeholder moon orbiting ${planet.name}.`
    }, "Moon");
    moon.type = BODY_TYPES.MOON;
    linkChild(bodies, planet.id, moon);
  }
}

export function createAutopopulatedSystem(options = {}) {
  const seed = options.seed || `${Date.now()}`;
  const rng = makeRng(seed);
  const starMode = options.starMode === "binary" ? "binary" : "single";
  const planetCount = Number.isFinite(options.planetCount) ? options.planetCount : 6;
  const maxMoons = Number.isFinite(options.maxMoons) ? options.maxMoons : 3;
  const figure8Chance = Number.isFinite(options.figure8Chance) ? options.figure8Chance : 0.12;
  const dualPlanetChance = Number.isFinite(options.dualPlanetChance) ? options.dualPlanetChance : 0.18;

  const bodies = [makeRoot()];
  const metadata = {
    version: 1,
    name: options.name || "Generated Star System",
    seed,
    timeScale: options.timeScale ?? DEFAULTS.timeScale,
    gravitationalConstant: options.gravitationalConstant ?? DEFAULTS.gravitationalConstant,
    viewState: { focusId: null, stack: [] },
    uiState: { selectedId: null, showHud: true },
    background: {
      color: colorToHex(options.backgroundColor || "#050816"),
      starsDensity: 130,
      nebulaStrength: 0.25
    }
  };

  let primaryAnchorId = "root-system";
  let binaryPrimaryId = null;
  let binarySecondaryId = null;

  if (starMode === "single") {
    const star = makeStar(rng, 0, { orbitMode: ORBIT_MODES.STATIC, parentId: "root-system", name: "Primary Star" });
    linkChild(bodies, "root-system", star);
    primaryAnchorId = star.id;
  } else {
    const starA = makeStar(rng, 0, {
      orbitMode: ORBIT_MODES.BINARY,
      parentId: "root-system",
      name: "Primary Star",
      semiMajorAxis: 105,
      eccentricity: 0.04,
      clockwise: false
    });
    const starB = makeStar(rng, 1, {
      orbitMode: ORBIT_MODES.BINARY,
      parentId: "root-system",
      name: "Companion Star",
      semiMajorAxis: 105,
      eccentricity: 0.04,
      clockwise: true
    });
    starA.orbit.partnerId = starB.id;
    starB.orbit.partnerId = starA.id;
    starA.orbit.binarySeparation = 210;
    starB.orbit.binarySeparation = 210;
    starA.orbit.phase = 0;
    starB.orbit.phase = Math.PI;
    linkChild(bodies, "root-system", starA);
    linkChild(bodies, "root-system", starB);
    primaryAnchorId = "root-system";
    binaryPrimaryId = starA.id;
    binarySecondaryId = starB.id;
  }

  let orbitalDistance = 260;
  for (let i = 0; i < planetCount; i += 1) {
    const useDualPlanet = rng() < dualPlanetChance;
    const useFigure8 = starMode === "binary" && rng() < figure8Chance;

    if (useDualPlanet) {
      const bary = makeBarycenter(`Dual Planet Barycenter ${i + 1}`, primaryAnchorId, {
        mode: useFigure8 ? ORBIT_MODES.FIGURE8 : ORBIT_MODES.KEPLER,
        phase: range(rng, 0, Math.PI * 2),
        semiMajorAxis: orbitalDistance,
        eccentricity: range(rng, 0, 0.14),
        primaryId: starMode === "single" ? primaryAnchorId : binaryPrimaryId,
        secondaryId: starMode === "binary" ? binarySecondaryId : null,
        figure8Scale: orbitalDistance * 0.48,
        inclination: range(rng, -0.12, 0.12)
      });
      linkChild(bodies, primaryAnchorId, bary);

      const p1 = makePlanet(rng, i, bary.id, {
        name: `Twin Planet ${i + 1}A`,
        mode: ORBIT_MODES.BINARY,
        phase: 0,
        semiMajorAxis: 36,
        eccentricity: range(rng, 0, 0.08),
        binarySeparation: 72
      }, "Twin Planet");
      const p2 = makePlanet(rng, i, bary.id, {
        name: `Twin Planet ${i + 1}B`,
        mode: ORBIT_MODES.BINARY,
        phase: Math.PI,
        semiMajorAxis: 36,
        eccentricity: range(rng, 0, 0.08),
        binarySeparation: 72
      }, "Twin Planet");
      p1.orbit.partnerId = p2.id;
      p2.orbit.partnerId = p1.id;
      linkChild(bodies, bary.id, p1);
      linkChild(bodies, bary.id, p2);
      addMoons({ rng, bodies, planet: p1, maxMoons });
      addMoons({ rng, bodies, planet: p2, maxMoons: Math.max(0, maxMoons - 1) });
    } else {
      const orbitMode = useFigure8 ? ORBIT_MODES.FIGURE8 : ORBIT_MODES.KEPLER;
      const planet = makePlanet(rng, i, primaryAnchorId, {
        mode: orbitMode,
        semiMajorAxis: orbitalDistance,
        eccentricity: range(rng, 0, 0.16),
        primaryId: starMode === "single" ? primaryAnchorId : binaryPrimaryId,
        secondaryId: starMode === "binary" ? binarySecondaryId : null,
        figure8Scale: orbitalDistance * 0.52,
        inclination: range(rng, -0.14, 0.14)
      });
      linkChild(bodies, primaryAnchorId, planet);
      addMoons({ rng, bodies, planet, maxMoons });
    }

    orbitalDistance *= range(rng, 1.26, 1.43);
  }

  return { metadata, bodies };
}
